export default [

    {   
        eventName: "Frozen Darkness",
        eventImage: require("../../assets/Images/Events/FrozenDarkness.png"),
        currentEvent: 'n',
        Character1Name: 'Lucia - Crimson Abyss',
        Character1Image: require('../../assets/Images/CrimsonAbyss/Construct_CrimsonAbyss.png'),
    },
    {
        eventName: "Fallen Star",
        eventImage: require("../../assets/Images/Events/FallenStar.png"),
        currentEvent: 'n',
        Character1Name: 'Ayla - Brilliance',
        Character1Image: require('../../assets/Images/Brilliance/Construct_Brilliance.png'),
        Character2Name: 'Watanabe-Astral',
        Character2Image: require('../../assets/Images/Astral/Construct_Astral.png'),
    },
    {
        eventName: "Eternal Engine",
        eventImage: require("../../assets/Images/Events/EternalEngine.png"),
        currentEvent: 'n',
        Character1Name: 'Bianca - Veritas',
        Character1Image: require('../../assets/Images/Veritas/Construct_Veritas.png'),
    },
    {
        eventName: "Nona Ouroboros",
        eventImage: require("../../assets/Images/Events/NonaOuroboros.png"),
        currentEvent: 'n',
        Character1Name: 'Chrome - Arclight',
        Character1Image: require('../../assets/Images/Arclight/Construct_Arclight.png'),
    },
    {
        eventName: "Kowloong Metropolis",
        eventImage: require("../../assets/Images/Events/KowloongMetropolis.png"),
        currentEvent: 'n',
        Character1Name: 'Lucia - Plume',
        Character1Image: require('../../assets/Images/Plume/Construct_Plume.png'),
    },
    {
        eventName: "Grand Blue",
        eventImage: require("../../assets/Images/Events/GrandBlue.png"),
        currentEvent: 'y',
        Character1Name: 'Vera - Rozen',
        Character1Image: require('../../assets/Images/Rozen/Construct_Rozen.png'),
    },
    {
        eventName: "Firn Night",
        eventImage: require("../../assets/Images/Events/FirnNight.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Lost Chapter",
        eventImage: require("../../assets/Images/Events/LostChapter.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Fake Ascension",
        eventImage: require("../../assets/Images/Events/FakeAscension.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Untold Naraka",
        eventImage: require("../../assets/Images/Events/UntoldNaraka.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Echo Aria",
        eventImage: require("../../assets/Images/Events/EchoAria.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Imprisoned Sight",
        eventImage: require("../../assets/Images/Events/ImprisonedSight.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Inscryption of Labyrinth",
        eventImage: require("../../assets/Images/Events/InscriptionofLabyrinth.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "The Last Spark",
        eventImage: require("../../assets/Images/Events/TheLastSpark.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Evernight Beat",
        eventImage: require("../../assets/Images/Events/EvernightBeat.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "The Survival Lucem",
        eventImage: require("../../assets/Images/Events/TheSurvivalLucem.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Recitative de Fantasia",
        eventImage: require("../../assets/Images/Events/RecitativedeFantasia.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Wandering Dream with Whale",
        eventImage: require("../../assets/Images/Events/WanderingDream.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
    {
        eventName: "Her Last Bow",
        eventImage: require("../../assets/Images/Events/HerLastBow.png"),
        currentEvent: 'n',
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '2B',
        Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    },
];