export default [

    {   
        id: 0,
        eventName: "Frozen Darkness",
        eventImage: require("../../assets/Images/Events/FrozenDarkness.png"),
        currentEvent: 'n',
        amountOfCharacters: 1,
        Character1Name: 'Lucia - Crimson Abyss',
        Character1Image: require('../../assets/Images/CrimsonAbyss/Construct_CrimsonAbyss.png'),
    },
    {
        id: 1,
        eventName: "Fallen Star",
        eventImage: require("../../assets/Images/Events/FallenStar.png"),
        currentEvent: 'n',
        amountOfCharacters: 2,
        Character1Name: 'Ayla - Brilliance',
        Character1Image: require('../../assets/Images/Brilliance/Construct_Brilliance.png'),
        Character2Name: 'Watanabe-Astral',
        Character2Image: require('../../assets/Images/Astral/Construct_Astral.png'),
    },
    {
        id: 2,
        eventName: "Eternal Engine",
        eventImage: require("../../assets/Images/Events/EternalEngine.png"),
        currentEvent: 'n',
        amountOfCharacters: 1,
        Character1Name: 'Bianca - Veritas',
        Character1Image: require('../../assets/Images/Veritas/Construct_Veritas.png'),
    },
    {
        id: 3,
        eventName: "Nona Ouroboros",
        eventImage: require("../../assets/Images/Events/NonaOuroboros.png"),
        currentEvent: 'n',
        amountOfCharacters: 2,
        Character1Name: 'Chrome - Arclight',
        Character1Image: require('../../assets/Images/Arclight/Construct_Arclight.png'),
        
    },
    {
        id: 4,
        eventName: "Kowloong Metropolis",
        eventImage: require("../../assets/Images/Events/KowloongMetropolis.png"),
        currentEvent: 'n',
        amountOfCharacters: 1,
        Character1Name: 'Lucia - Plume',
        Character1Image: require('../../assets/Images/Plume/Construct_Plume.png'),
    },
    //GrandBlue
    {
        id: 5,
        eventName: "Grand Blue",
        eventImage: require("../../assets/Images/Events/GrandBlue.png"),
        currentEvent: 'n',
        amountOfCharacters: 2,
        Character1Name: 'Vera - Rozen',
        Character1Image: require('../../assets/Images/Rozen/Construct_Rozen.png'),
        Character2Name: 'Camu - Crocotta',
        Character2Image: require('../../assets/Images/Crocotta/Construct_Crocotta.png'),
    },
    //Firn Night
    {
        id: 6,
        eventName: "Firn Night",
        eventImage: require("../../assets/Images/Events/FirnNight.png"),
        currentEvent: 'y',
        amountOfCharacters: 1,
        Character1Name: 'Rosetta - Rigor',
        Character1Image: require('../../assets/Images/Arctic/Construct_Arctic.png'),
    },
    //Lost Chapter
    {
        id: 7,
        eventName: "Lost Chapter",
        eventImage: require("../../assets/Images/Events/LostChapter.png"),
        currentEvent: 'u',
        amountOfCharacters: 2,
        Character1Name: 'Changyu - Kirin',
        Character1Image: require('../../assets/Images/Kirin/Construct_Kirin.png'),
        Character2Name: "Qu-Peafowl's Plume",
        Character2Image: require('../../assets/Images/Peafowl/Construct_Peafowl.png'),
    },
    {
        id: 8,
        eventName: "Fake Ascension",
        eventImage: require("../../assets/Images/Events/FakeAscension.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'Luna - Laurel',
        Character1Image: require('../../assets/Images/Laurel/Construct_Laurel.png'),
    },
    {
        id: 9,
        eventName: "Untold Naraka",
        eventImage: require("../../assets/Images/Events/UntoldNaraka.png"),
        currentEvent: 'u',
        amountOfCharacters: 3,
        Character1Name: '2B',
        Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
        Character2Name: '9S',
        Character2Image: require('../../assets/Images/9S/Construct_9S.png'),
        Character3Name: 'A2',
        Character3Image: require('../../assets/Images/A2/Construct_A2.png'),
    },
    //Echo Aria
    {
        id: 10,
        eventName: "Echo Aria",
        eventImage: require("../../assets/Images/Events/EchoAria.png"),
        currentEvent: 'u',
        amountOfCharacters: 2,
        Character1Name: 'Wanshi - Fate',
        Character1Image: require('../../assets/Images/Fate/Construct_Fate.png'),
        Character2Name: 'Selena - Tempest',
        Character2Image: require('../../assets/Images/Tempest/Construct_Tempest.png'),
    },
    {
        id: 11,
        eventName: "Imprisoned Sight",
        eventImage: require("../../assets/Images/Events/ImprisonedSight.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'Chrome - Glory',
        Character1Image: require('../../assets/Images/Glory/Construct_Glory.png'),
    },
    {
        id: 12,
        eventName: "Inscryption of Labyrinth",
        eventImage: require("../../assets/Images/Events/InscriptionofLabyrinth.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'No.21 - XXI',
        Character1Image: require('../../assets/Images/XXI/Construct_XXI.png'),
    },
    //The Last Spark
    {
        id: 13,
        eventName: "The Last Spark",
        eventImage: require("../../assets/Images/Events/TheLastSpark.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'Vera - Flare',
        Character1Image: require('../../assets/Images/Flare/Construct_Flare.png'),
    },
    //Evernight Beat
    {
        id: 14,
        eventName: "Evernight Beat",
        eventImage: require("../../assets/Images/Events/EvernightBeat.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'Roland - Theatrical Flame',
        Character1Image: require('../../assets/Images/Theatrical/Construct_Theatrical.png'),
    },
    {
        id: 15,
        eventName: "The Survival Lucem",
        eventImage: require("../../assets/Images/Events/TheSurvivalLucem.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'Liv - Solaeter',
        Character1Image: require('../../assets/Images/Solaeter/Construct_Solaeter.png'),
        
    },
    {
        id: 16,
        eventName: "Recitative de Fantasia",
        eventImage: require("../../assets/Images/Events/RecitativedeFantasia.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'Selena - Capriccio',
        Character1Image: require('../../assets/Images/Capriccio/Construct_Capriccio.png'),
    },
    //Whale
    {
        id: 17,
        eventName: "Wandering Dream with Whale",
        eventImage: require("../../assets/Images/Events/WanderingDream.png"),
        currentEvent: 'u',
        amountOfCharacters: 1,
        Character1Name: 'Pulao - Ornate Bell',
        Character1Image: require('../../assets/Images/Ornate/Construct_Ornate.png'),
    },
    // {
    // id: 097,
    //     eventName: "Her Last Bow",
    //     eventImage: require("../../assets/Images/Events/HerLastBow.png"),
    //     currentEvent: 'u',
    //     amountOfCharacters: 2,
    //     Character1Name: '2B',
    //     Character1Image: require('../../assets/Images/2B/Construct_2B.png'),
    //     Character2Name: '2B',
    //     Character2Image: require('../../assets/Images/2B/Construct_2B.png'),
    // },
];